import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, unlink } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import type { AppConfig } from '../../../config/configuration';
import type { StorageProvider, StoredObject } from '../storage.interface';

/**
 * Writes uploads under `STORAGE_LOCAL_PATH`.
 *
 * Keys are generated by the service — the original filename never becomes a path — so a request
 * cannot escape the storage root by sending `../` in a name.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local';
  private readonly root: string;
  private readonly publicBase: string;

  constructor(config: AppConfig) {
    this.root = resolve(config.storage.localPath);
    this.publicBase = config.storage.publicUrl.replace(/\/$/, '');
  }

  async put(key: string, body: Buffer, _mimeType: string): Promise<StoredObject> {
    const absolute = this.resolveKey(key);
    await mkdir(dirname(absolute), { recursive: true });
    await pipeline(Readable.from(body), createWriteStream(absolute));
    return { key, sizeBytes: body.length };
  }

  async get(key: string): Promise<Buffer> {
    const absolute = this.resolveKey(key);
    const chunks: Buffer[] = [];
    const stream = createReadStream(absolute);

    for await (const chunk of stream) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }

    return Buffer.concat(chunks);
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.resolveKey(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }
  }

  publicUrl(key: string): string {
    return `${this.publicBase}/${encodeURIComponent(key)}`;
  }

  private resolveKey(key: string): string {
    const normalised = key.replace(/\\/g, '/').replace(/^\/+/, '');
    const absolute = resolve(this.root, ...normalised.split('/'));
    const prefix = this.root.endsWith(sep) ? this.root : `${this.root}${sep}`;

    if (absolute !== this.root && !absolute.startsWith(prefix)) {
      throw new Error('Storage key escaped the configured root');
    }

    return join(this.root, ...normalised.split('/'));
  }
}
