/** Canonical route table. Nothing in the applications hard-codes a path string. */

export const publicRoutes = {
  home: '/',
  plans: '/plans',
  planByCity: (citySlug: string) => `/plans/${citySlug}`,
  planDetail: (planSlug: string) => `/packages/${planSlug}`,
  products: '/products',
  internet: '/products/internet',
  tv: '/products/tv',
  phone: '/products/phone',
  getConnection: '/get-stormfiber',
  checkAvailability: '/check-availability',
  compare: '/plans/compare',
  support: '/support',
  supportBilling: '/support/billing',
  helpCenter: '/support/help-center',
  helpArticle: (slug: string) => `/support/help-center/${slug}`,
  contact: '/support/contact',
  faqs: '/faqs',
  faqCategory: (slug: string) => `/faqs/category/${slug}`,
  faqDetail: (slug: string) => `/faqs/${slug}`,
  offers: '/offers',
  offerDetail: (slug: string) => `/offers/${slug}`,
  terms: '/terms-and-conditions',
  privacy: '/privacy-policy',
  fairUsage: '/fair-usage-policy',
  coverageCities: '/coverage',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyMobile: '/verify-mobile',
} as const;

export const dashboardRoutes = {
  root: '/dashboard',
  profile: '/dashboard/profile',
  subscription: '/dashboard/subscription',
  billing: '/dashboard/billing',
  invoices: '/dashboard/invoices',
  invoiceDetail: (id: string) => `/dashboard/invoices/${id}`,
  payments: '/dashboard/payments',
  paymentReturn: '/dashboard/payments/return',
  tickets: '/dashboard/tickets',
  ticketNew: '/dashboard/tickets/new',
  ticketDetail: (id: string) => `/dashboard/tickets/${id}`,
  notifications: '/dashboard/notifications',
  settings: '/dashboard/settings',
} as const;

export const adminRoutes = {
  login: '/login',
  dashboard: '/dashboard',
  customers: '/customers',
  customerDetail: (id: string) => `/customers/${id}`,
  applications: '/applications',
  applicationDetail: (id: string) => `/applications/${id}`,
  subscriptions: '/subscriptions',
  plans: '/plans',
  planEdit: (id: string) => `/plans/${id}`,
  planNew: '/plans/new',
  addons: '/plans/addons',
  promotions: '/plans/promotions',
  products: '/products',
  cities: '/cities',
  areas: '/areas',
  coverage: '/coverage',
  invoices: '/invoices',
  invoiceDetail: (id: string) => `/invoices/${id}`,
  payments: '/payments',
  tickets: '/tickets',
  ticketDetail: (id: string) => `/tickets/${id}`,
  callbacks: '/callbacks',
  content: '/content',
  heroSlides: '/content/hero-slides',
  pages: '/content/pages',
  faqs: '/faqs',
  offers: '/offers',
  users: '/users',
  roles: '/roles',
  analytics: '/analytics',
  auditLogs: '/audit-logs',
  settings: '/settings',
} as const;

/** Public navigation tree. Mirrors the information architecture of the reference site. */
export interface NavItem {
  label: string;
  href: string;
  description?: string;
  external?: boolean;
  children?: NavItem[];
}

export const primaryNavigation: NavItem[] = [
  { label: 'Plans', href: publicRoutes.plans },
  {
    label: 'Products',
    href: publicRoutes.products,
    children: [
      {
        label: 'Ultra-Fast Internet',
        href: publicRoutes.internet,
        description: 'Symmetric fibre speeds with no volume cap',
      },
      {
        label: 'HD TV',
        href: publicRoutes.tv,
        description: 'Hundreds of channels on a single fibre line',
      },
      {
        label: 'Crystal Clear Voice',
        href: publicRoutes.phone,
        description: 'A landline that works even without mobile signal',
      },
    ],
  },
  {
    label: 'Support',
    href: publicRoutes.support,
    children: [
      { label: 'Billing & Payments', href: publicRoutes.supportBilling },
      { label: 'Help Center', href: publicRoutes.helpCenter },
      { label: 'Get in Touch', href: publicRoutes.contact },
    ],
  },
  { label: 'Offers', href: publicRoutes.offers },
];

export const utilityNavigation: NavItem[] = [
  { label: 'Check Availability', href: publicRoutes.checkAvailability },
  { label: 'Sign In', href: publicRoutes.login },
];

export const dashboardNavigation: NavItem[] = [
  { label: 'Overview', href: dashboardRoutes.root },
  { label: 'My Subscription', href: dashboardRoutes.subscription },
  { label: 'Billing', href: dashboardRoutes.billing },
  { label: 'Invoices', href: dashboardRoutes.invoices },
  { label: 'Payments', href: dashboardRoutes.payments },
  { label: 'Support Tickets', href: dashboardRoutes.tickets },
  { label: 'Notifications', href: dashboardRoutes.notifications },
  { label: 'Profile', href: dashboardRoutes.profile },
  { label: 'Settings', href: dashboardRoutes.settings },
];

/** API paths, relative to the versioned base URL. */
export const apiRoutes = {
  health: '/health',
  cities: '/cities',
  cityAreas: (slug: string) => `/cities/${slug}/areas`,
  areaSubAreas: (id: string) => `/areas/${id}/subareas`,
  coverageCheck: '/coverage/check',
  coverageLeads: '/coverage/leads',
  coverageSummary: '/coverage/summary',
  plans: '/plans',
  planBySlug: (slug: string) => `/plans/${slug}`,
  planCategories: '/plans/categories',
  planAddons: '/plans/addons',
  planCompare: '/plans/compare',
  priceQuote: '/pricing/quote',
  products: '/products',
  productBySlug: (slug: string) => `/products/${slug}`,
  promotions: '/offers',
  promotionBySlug: (slug: string) => `/offers/${slug}`,
  faqs: '/faqs',
  faqBySlug: (slug: string) => `/faqs/${slug}`,
  faqCategories: '/faqs/categories',
  supportCategories: '/support/categories',
  cmsPage: (slug: string) => `/cms/pages/${slug}`,
  cmsSections: '/cms/sections',
  heroSlides: '/cms/hero-slides',
  siteSettings: '/cms/site-settings',
  callbacks: '/callbacks',
  analyticsEvents: '/analytics/events',

  authRegister: '/auth/register',
  authLogin: '/auth/login',
  authLogout: '/auth/logout',
  authRefresh: '/auth/refresh',
  authMe: '/auth/me',
  authOtpRequest: '/auth/otp/request',
  authOtpVerify: '/auth/otp/verify',
  authForgotPassword: '/auth/forgot-password',
  authResetPassword: '/auth/reset-password',
  authChangePassword: '/auth/change-password',
  authSessions: '/auth/sessions',

  applications: '/applications',
  applicationById: (id: string) => `/applications/${id}`,
  applicationSubmit: (id: string) => `/applications/${id}/submit`,

  customerProfile: '/customer/profile',
  customerSubscription: '/customer/subscription',
  customerSubscriptionChange: '/customer/subscription/change-requests',
  customerInvoices: '/customer/invoices',
  customerInvoiceById: (id: string) => `/customer/invoices/${id}`,
  customerInvoicePdf: (id: string) => `/customer/invoices/${id}/pdf`,
  customerPayments: '/customer/payments',
  customerBillingSummary: '/customer/billing/summary',
  customerNotifications: '/customer/notifications',
  customerApplications: '/customer/applications',

  payments: '/payments',
  paymentById: (id: string) => `/payments/${id}`,
  paymentWebhook: '/payments/webhook',

  tickets: '/tickets',
  ticketById: (id: string) => `/tickets/${id}`,
  ticketMessages: (id: string) => `/tickets/${id}/messages`,

  uploads: '/files/upload',

  admin: {
    dashboard: '/admin/analytics/dashboard',
    charts: '/admin/analytics/charts',
    customers: '/admin/customers',
    applications: '/admin/applications',
    subscriptions: '/admin/subscriptions',
    plans: '/admin/plans',
    planPrices: '/admin/plans/prices',
    addons: '/admin/plans/addons',
    promotions: '/admin/promotions',
    products: '/admin/products',
    cities: '/admin/cities',
    areas: '/admin/areas',
    subAreas: '/admin/subareas',
    coverage: '/admin/coverage',
    invoices: '/admin/invoices',
    payments: '/admin/payments',
    refunds: '/admin/refunds',
    tickets: '/admin/tickets',
    callbacks: '/admin/callbacks',
    content: '/admin/content',
    heroSlides: '/admin/content/hero-slides',
    pages: '/admin/content/pages',
    sections: '/admin/content/sections',
    faqs: '/admin/faqs',
    faqCategories: '/admin/faqs/categories',
    users: '/admin/users',
    roles: '/admin/roles',
    permissions: '/admin/permissions',
    auditLogs: '/admin/audit-logs',
    settings: '/admin/settings',
    leads: '/admin/coverage/leads',
  },
} as const;
